proxy: proxy_server.c
	cc -o proxy_server proxy_server.c common.c acl.c -lwrap

tetris: tetris.c
	cc -o tetris tetris.c common.c acl.c -lwrap

client: cloud_client.c
	cc -o cloud_client cloud_client.c common.c acl.c -lwrap
